### ISSUE TITLE
Foundation • Typographic System

### ISSUE THREAD

**Issue by codingwithchris** [the-playground/weareplayground.org#12]
## Overview
Build and implement a custom typographic system.

## Todo
- [x] Integrate & configure custom grunge heading font
- [x] Load & configure standard heading font
- [x] Load & configure body font
- [x] Elegantly handle font-loading
- [x] Implement typographic scale
- [x] Build typography components

## Todo Before PR
- [x] Validate props for typography components
